name: GitHub Metrics
on:
  schedule:
    - cron: "30 5,17 * * *"
  workflow_dispatch:
  
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  USER_NAME: DennisLin0125
  CONFIG_TIMEZONE: Etc/GMT-8

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: svg/github-metrics.svg
          token: ${{ env.GH_TOKEN }}
          user: ${{ env.USER_NAME }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: ${{ env.CONFIG_TIMEZONE }}

      - name: Comment Reactions
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.reactions.svg
          token: ${{ env.GH_TOKEN }}
          user: ${{ env.USER_NAME }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
          config_timezone: ${{ env.CONFIG_TIMEZONE }}

      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.stars.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
      
      # 🈷️ Languages activit
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.languages.details.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: lines, bytes-size
          # plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          
      - name: Recently used
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.languages.recent.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.activity.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: push, pr, public, fork, review, ref/create

      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.calendar.full.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
      
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.habits.charts.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
      
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.achievements.compact.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - name: Pinned repositories
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.repositories.pinned.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 2
          

       # 🎟️ Follow-up of issues and pull requests 
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: svg/followup.indepth.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

       # ✨ Stargazers   
      - name: Using chartist charts
        uses: lowlighter/metrics@latest
        with:
          filename: svg/stargazers.chartist.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
      
      - name: Using classic charts
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.stargazers.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_stargazers: yes

      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Top answers from stackoverflow
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.stackoverflow.svg
          token: NOT_NEEDED
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 1
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2

      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: svg/metrics.plugin.people.followers.svg
          token: ${{ env.GH_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers




